### ISSUE TITLE
Refactor Readme

### ISSUE THREAD

**Issue by mJace** [ITRI-ICL-Peregrine/x-tracer#14]
**Refactor readme**
Currently readme file is giving too much unnecessary information.
Please refactor it into a simple way.
Can take https://github.com/ITRI-ICL-Peregrine/x-k8s as a reference.

You could create a folder called `docs` to store the detailed documents.

**Comment by mJace** [comment]
these spec are already known or fixed.
Ubuntu 18.04 LTS server  
Kubernetes v1.16  
for these other spec like kernel version, you could define them by your own.
As long as the released x-tracer works on these specs.

**Comment by Sheenam3** [comment]
Will update README with the testing specs
