### ISSUE TITLE
Error when using 'all probes'

### ISSUE THREAD

**Issue by mJace** [ITRI-ICL-Peregrine/x-tracer#37]
![image](https://user-images.githubusercontent.com/9836691/101305054-afb66b00-387c-11eb-9f78-2db62640a170.png)

Same env in README.
test pod with ubuntu, and command is 'apt-get update'

**Comment by Sheenam3** [comment]
**Reason:**
alignment/space issue in Biosnoop probe as you can see from the logs _Network namespace_ and _bytes_ column merged into one which caused the crash with `index out of range error`:- 

![biosnoop error december](https://user-images.githubusercontent.com/45314018/101312852-c7e3b580-388f-11eb-827f-b758870324da.png)

**Solution:**
Already fixed and tested by executing the following command inside the pod's container:
apt-get update
apt-get install gnome
